export default [
    {
      question: "Quando você resolve um problema, o que te traz mais satisfação?",
      answers: [
        { option: " Encontrar a solução mais eficiente e prática usando lógica e análise", course: "T.I., ADS"},
        { option: "Ver o impacto visual da solução, algo que as pessoas podem admirar ", course: "Web Design, Designer Gráfico" },
        { option: "Organizar a informação de forma clara e objetiva para facilitar a tomada de decisões", course: "Operador de Dados" },
        { option: "Ajudar as pessoas a compreenderem algo ou a se sentirem mais conectadas", course: "Soft Skills" },
        { option: " Ver um projeto ser executado conforme o planejamento e alcançar o sucesso", course: "Administração"},
        { option: "Saber que você fez a diferença direta na vida de alguém, seja cuidando ou oferecendo suporte", course: "Profissional de Saúde"},
        { option: "Criar algo que envolva e divirta outras pessoas, inspirando novas experiências ", course: "Desenvolvedor de Games" },
        { option: " Produzir materiais visuais criativos e práticos para campanhas e projetos", course: "Gráfico" },
        { option: "Desenvolver campanhas estratégicas que alcancem o público certo", course: "Marketing Digital" },
      ],
    },
    {
      question: "O que te motiva mais no seu trabalho diário?",
      answers: [
        { option: "Resolver problemas desafiadores que requerem raciocínio lógico", course: "T.I., ADS" },
        { option: "Trabalhar em algo visualmente criativo e inovador ", course: "Web Design, Designer Gráfico"},
        { option: "Organizar sistemas complexos e torná-los fáceis de entender", course: "Operador de Dados"},
        { option: "Desenvolver a comunicação e o entendimento entre as pessoas", course: "Soft Skills" },
        { option: "Ter controle sobre o progresso de um projeto e liderar o caminho até o sucesso", course: "Administração" },
        { option: "Cuidar das necessidades físicas e emocionais dos outros", course: "Profissional de Saúde" },
        { option: "Projetar mundos e histórias que envolvem outras pessoas em suas criações", course: "Desenvolvedor de Games" },
        { option: "Trabalhar com peças gráficas que ajudam a transmitir uma mensagem de forma eficaz", course: "Gráfico"},
        { option: "Criar estratégias de comunicação e marketing digital que gerem resultados", course: "Marketing Digital" },
      ],
    },
    {
      question: " Qual é a sua relação com os desafios emocionais?",
      answers: [
        { option: "Prefiro lidar com problemas concretos e técnicos, evitando muita carga emocional", course: "T.I., ADS"},
        { option: "Uso meus sentimentos como inspiração para criar algo bonito e expressivo", course: "Web Design, Designer Gráfico"},
        { option: "Lido melhor com dados e lógica, mas aprendo a enfrentar desafios emocionais quando necessário", course: "Operador de Dados"},
        { option: "Encaro os desafios emocionais de frente, ajudando os outros a encontrar equilíbrio", course: "Soft Skills"},
        { option: "Tento ser objetivo, mas reconheço a importância das emoções para liderar com empatia", course: "Administração"},
        { option: "Abraço os desafios emocionais, pois acredito que o cuidado começa ao entender as emoções das pessoas", course: "Profissional de Saúde"},
        { option: "Uso emoções para criar histórias e personagens que expressam o que sinto ou o que observo", course: "Desenvolvedor de Games"},
        { option: "Uso as emoções para criar materiais visuais impactantes", course: "Gráfico"},
        { option: "Exploro o comportamento humano para criar campanhas eficazes", course: "Marketing Digital"},
      ],
    },
    {
      question: "  O que te faz sentir mais realizado no final de um dia de trabalho?",
      answers: [
        { option: "Saber que consegui resolver um problema difícil com minhas habilidades técnicas", course: "T.I., ADS" },
        { option: "Ver algo que criei sendo admirado por sua estética e impacto visual", course: "Web Design, Designer Gráfico"},
        { option: "Ter organizado e estruturado informações de forma clara e útil", course: "Operador de Dados"},
        { option: "Ver que ajudei alguém a se desenvolver ou a entender melhor a si mesmo ou aos outros", course: "Soft Skills"},
        { option: "Sentir que lidei com sucesso com as responsabilidades de liderança e gestão ", course: "Administração"},
        { option: "Saber que fiz algo para melhorar a saúde ou o bem-estar de alguém", course: "Profissional de Saúde"},
        { option: "Ver alguém se divertir ou ser impactado por algo que criei ", course: "Desenvolvedor de Games"},
        { option: "Ver uma peça gráfica que criei ser utilizada em campanhas importantes", course: "Gráfico"},
        { option: "Saber que minha campanha digital trouxe resultados mensuráveis para o cliente", course: "Marketing Digital"},
      ],
    },
    {
        question: " Quando você pensa no sucesso, o que ele significa para você?",
        answers: [
          { option: "Resolver problemas que os outros consideram impossíveis e ser reconhecido por minha habilidade técnica", course: "T.I., ADS" },
          { option: "Criar algo que as pessoas vão lembrar, algo que cause uma boa impressão visual", course: "Web Design, Designer Gráfico"},
          { option: "Ser capaz de organizar e interpretar grandes quantidades de informação de forma clara e eficiente ", course: "Operador de Dados"},
          { option: "Ajudar as pessoas a alcançar seus próprios sucessos, promovendo uma boa comunicação e entendimento", course: "Soft Skills"},
          { option: "Liderar projetos e equipes que tenham impacto real em uma organização ou sociedade ", course: "Administração"},
          { option: "Ser uma fonte de conforto e cuidado para aqueles que precisam, melhorando suas vidas", course: "Profissional de Saúde"},
          { option: "Criar algo inovador e envolvente que inspire outras pessoas", course: "Desenvolvedor de Games"},
          { option: "Produzir materiais gráficos que transmitam mensagens poderosas e diretas", course: "Gráfico"},
          { option: "Alcançar o público certo e gerar resultados eficazes com estratégias digitais", course: "Marketing Digital"},
        ],
      },
      {
        question: "  Como você lida com situações que estão fora do seu controle?",
        answers: [
          { option: "Tento encontrar soluções alternativas que dependam das minhas habilidades técnicas", course: "T.I., ADS"},
          { option: "Tento me adaptar e buscar inspiração criativa dentro das limitações", course: "Web Design, Designer Gráfico"},
          { option: "Tento reorganizar as informações e trabalhar com o que tenho de forma lógica", course: "Operador de Dados"},
          { option: "Foco em ajudar os outros a lidar com a situação, oferecendo suporte emocional", course: "Soft Skills"},
          { option: "Busco formas de retomar o controle da situação com liderança e planejamento", course: "Administração"},
          { option: "Aceito a situação e faço o melhor que posso para ajudar as pessoas envolvidas", course: "Profissional de Saúde"},
          { option: "Tento reimaginar a situação, criando soluções criativas e alternativas", course: "Desenvolvedor de Games"},
          { option: "Encontro maneiras de ajustar o projeto gráfico conforme a necessidade do cliente", course: "Gráfico"},
          { option: "Redireciono as estratégias digitais para alcançar os melhores resultados possíveis ", course: "Marketing Digital"},
        ],
      },
      {
        question: "O que é mais importante para você em um ambiente de trabalho?",
        answers: [
          { option: "Ter acesso a novas tecnologias e desafios complexos", course: "T.I., ADS"},
          { option: "Um ambiente que estimule a criatividade e a expressão visual ", course: "Web Design, Designer Gráfico"},
          { option: "Um espaço organizado e focado, onde eu possa trabalhar com dados e sistemas", course: "Operador de Dados"},
          { option: "Um lugar onde eu possa colaborar e desenvolver a comunicação com outras pessoas", course: "Soft Skills"},
          { option: "Um ambiente onde posso liderar e gerir projetos importantes", course: "Administração"},
          { option: "Um ambiente onde posso cuidar diretamente das pessoas e fazer a diferença na vida delas", course: "Profissional de Saúde" },
          { option: "Um espaço criativo onde posso imaginar e desenvolver novas ideias e jogos", course: "Desenvolvedor de Games"},
          { option: "Um ambiente que me permita trabalhar com comunicação visual e impressão", course: "Gráfico"},
          { option: "Um ambiente dinâmico onde estratégias e resultados de marketing estão sempre em evolução", course: "Marketing Digital"},
        ],
      },
      {
        question: "Como você lida com o fracasso?",
        answers: [
          { option: "Vejo o fracasso como uma oportunidade de melhorar minhas habilidades técnicas", course: "T.I., ADS"},
          { option: "Transformo o fracasso em inspiração para uma nova criação", course: "Web Design, Designer Gráfico"},
          { option: "Analiso o que deu errado para melhorar o processo no futuro", course: "Operador de Dados"},
          { option: "Uso o fracasso como uma oportunidade para aprender e ajudar outros a lidar com suas emoções", course: "Soft Skills"},
          { option: "Vejo o fracasso como um passo natural no caminho para o sucesso e aprendo com ele", course: "Administração"},
          { option: "Aceito o fracasso como parte do processo de cuidar das pessoas, e tento melhorar continuamente", course: "Profissional de Saúde"},
          { option: "Uso o fracasso como uma forma de melhorar minhas histórias e criações", course: "Desenvolvedor de Games"},
          { option: "Vejo o fracasso como uma oportunidade de refinar minhas peças gráficas", course: "Gráfico"},
          { option: "Reavalio a campanha e ajusto as estratégias para obter melhores resultados no futuro", course: "Marketing Digital"},
        ],
      },
      {
        question: "O que te faz sentir mais conectado com os outros?",
        answers: [
          { option: "Colaborar em projetos tecnológicos e resolver problemas em equipe", course: "T.I., ADS"},
          { option: "Compartilhar minhas criações visuais e ouvir feedback sobre elas", course: "Web Design, Designer Gráfico"},
          { option: "Ajudar a organizar e estruturar informações que ajudam as pessoas", course: "Operador de Dados" },
          { option: "Estar presente para os outros, ouvindo e ajudando-os a se expressarem melhor", course: "Soft Skills"},
          { option: "Trabalhar em equipe para alcançar metas e resolver problemas organizacionais", course: "Administração"},
          { option: "Cuidar das necessidades dos outros, mostrando empatia e compreensão", course: "Profissional de Saúde"},
          { option: "Criar algo em conjunto, como um jogo ou uma experiência que diverte as pessoas", course: "Desenvolvedor de Games"},
          { option: "Colaborar em projetos gráficos que comunicam mensagens importantes", course: "Gráfico"},
          { option: "Desenvolver campanhas que atingem o público de forma impactante e positiva", course: "Marketing Digital"},
        ],
      },
      {
        question: "Ao realizar uma tarefa em grupo, você prefere:",
        answers: [
          { option: "Assumir o comando e tomar decisões rápidas.", profile: "Dominância" },
          { option: "Motivar e engajar os outros com ideias e sugestões. ", profile: "Influência" },
          { option: "Garantir que todos se sintam confortáveis e seguros no grupo. ", profile: "Estabilidade" },
          { option: "Organizar as etapas e garantir que cada detalhe seja seguido corretamente. ", profile: "Conformidade" },
        ],
      },
      {
        question: "Quando enfrenta um desafio no trabalho ou nos estudos, você tende a:",
        answers: [
          { option: "Resolver o problema rapidamente, focando nos resultados.", profile: "Dominância" },
          { option: "Buscar apoio e opiniões de outras pessoas para encontrar a solução. ", profile: "Influência" },
          { option: "Agir com calma, analisando o impacto de cada escolha.", profile: "Estabilidade" },
          { option: "Seguir regras e procedimentos para encontrar a melhor solução. ", profile: "Conformidade"},
        ],
      },
      {
        question: "Qual dessas atividades mais lhe atrai?",
        answers: [
          { option: "Resolver problemas matemáticos ou desafios lógicos.", field: "Exatas Matemática e Lógica" },
          { option: "Escrever textos ou analisar questões sociais.", field: "Humanas Letras e Ciências Sociais"},
          { option: "Trabalhar com experimentos ou descobrir como algo funciona. ", field: "Exatas Ciências e Tecnologia"},
          { option: " Entender o comportamento humano e ajudar pessoas.", field: "Humanas Psicologia e Comportamento"},
        ],
      },
      {
        question: "Diante de um novo projeto, o que mais chama sua atenção?",
        answers: [
          { option: "Como estruturar e medir os resultados.", field: "Exatas Planejamento e Engenharia"},
          { option: "Como engajar as pessoas e comunicar ideias.", field: "Humanas Comunicação e Marketing"},
          { option: "Quais tecnologias podem ser usadas para otimizar o processo.", field: "Exatas Tecnologia e Inovação"},
          { option: "Como o projeto pode impactar positivamente a vida das pessoas.", field: "Humanas Desenvolvimento Social"},
        ],
      },
  ];