export default [
    {
      id: "pergunta1",
      question: "Pergunta 1: Quando você resolve um problema, o que te traz mais satisfação?",
      answers: [
        { option: "1- Encontrar a solução mais eficiente e prática usando lógica e análise", course: "T.I., ADS", },
        { option: "2- Ver o impacto visual da solução, algo que as pessoas podem admirar ", course: "Web Design, Designer Gráfico" },
        { option: "3- Organizar a informação de forma clara e objetiva para facilitar a tomada de decisões", course: "Operador de Dados" },
        { option: "4- Ajudar as pessoas a compreenderem algo ou a se sentirem mais conectadas", course: "Soft Skills" },
        { option: "5- Ver um projeto ser executado conforme o planejamento e alcançar o sucesso", course: "Administração"},
        { option: "6- Saber que você fez a diferença direta na vida de alguém, seja cuidando ou oferecendo suporte", course: "Profissional de Saúde"},
        { option: "7- Criar algo que envolva e divirta outras pessoas, inspirando novas experiências ", course: "Desenvolvedor de Games" },
        { option: "8- Produzir materiais visuais criativos e práticos para campanhas e projetos", course: "Gráfico" },
        { option: "9- Desenvolver campanhas estratégicas que alcancem o público certo", course: "Marketing Digital" },
      ],
    },
    {
      id: "pergunta2",
      question: "Pergunta 2: O que te motiva mais no seu trabalho diário?",
      answers: [
        { option: "1- Resolver problemas desafiadores que requerem raciocínio lógico", course: "T.I., ADS" },
        { option: "2- Trabalhar em algo visualmente criativo e inovador ", course: "Web Design, Designer Gráfico"},
        { option: "3- Organizar sistemas complexos e torná-los fáceis de entender", course: "Operador de Dados"},
        { option: "4- Desenvolver a comunicação e o entendimento entre as pessoas", course: "Soft Skills" },
        { option: "5- Ter controle sobre o progresso de um projeto e liderar o caminho até o sucesso", course: "Administração" },
        { option: "6- Cuidar das necessidades físicas e emocionais dos outros", course: "Profissional de Saúde" },
        { option: "7- Projetar mundos e histórias que envolvem outras pessoas em suas criações", course: "Desenvolvedor de Games" },
        { option: "8- Trabalhar com peças gráficas que ajudam a transmitir uma mensagem de forma eficaz", course: "Gráfico"},
        { option: "9- Criar estratégias de comunicação e marketing digital que gerem resultados", course: "Marketing Digital" },
      ],
    },
    {
      id: "pergunta3",
      question: "Pergunta 3: Qual é a sua relação com os desafios emocionais?",
      answers: [
        { option: "1- Prefiro lidar com problemas concretos e técnicos, evitando muita carga emocional", course: "T.I., ADS"},
        { option: "2- Uso meus sentimentos como inspiração para criar algo bonito e expressivo", course: "Web Design, Designer Gráfico"},
        { option: "3- Lido melhor com dados e lógica, mas aprendo a enfrentar desafios emocionais quando necessário", course: "Operador de Dados"},
        { option: "4- Encaro os desafios emocionais de frente, ajudando os outros a encontrar equilíbrio", course: "Soft Skills"},
        { option: "5- Tento ser objetivo, mas reconheço a importância das emoções para liderar com empatia", course: "Administração"},
        { option: "6- Abraço os desafios emocionais, pois acredito que o cuidado começa ao entender as emoções das pessoas", course: "Profissional de Saúde"},
        { option: "7- Uso emoções para criar histórias e personagens que expressam o que sinto ou o que observo", course: "Desenvolvedor de Games"},
        { option: "8- Uso as emoções para criar materiais visuais impactantes", course: "Gráfico"},
        { option: "9- Exploro o comportamento humano para criar campanhas eficazes", course: "Marketing Digital"},
      ],
    },
    {
      id: "pergunta4",
      question: "Pergunta 4: O que te faz sentir mais realizado no final de um dia de trabalho?",
      answers: [
        { option: "1- Saber que consegui resolver um problema difícil com minhas habilidades técnicas", course: "T.I., ADS" },
        { option: "2- Ver algo que criei sendo admirado por sua estética e impacto visual", course: "Web Design, Designer Gráfico"},
        { option: "3- Ter organizado e estruturado informações de forma clara e útil", course: "Operador de Dados"},
        { option: "4- Ver que ajudei alguém a se desenvolver ou a entender melhor a si mesmo ou aos outros", course: "Soft Skills"},
        { option: "5- Sentir que lidei com sucesso com as responsabilidades de liderança e gestão ", course: "Administração"},
        { option: "6- Saber que fiz algo para melhorar a saúde ou o bem-estar de alguém", course: "Profissional de Saúde"},
        { option: "7- Ver alguém se divertir ou ser impactado por algo que criei ", course: "Desenvolvedor de Games"},
        { option: "8- Ver uma peça gráfica que criei ser utilizada em campanhas importantes", course: "Gráfico"},
        { option: "9- Saber que minha campanha digital trouxe resultados mensuráveis para o cliente", course: "Marketing Digital"},
      ],
    },
    {
      id: "pergunta5",
        question: "Pergunta 5: Quando você pensa no sucesso, o que ele significa para você?",
        answers: [
          { option: "1- Resolver problemas que os outros consideram impossíveis e ser reconhecido por minha habilidade técnica", course: "T.I., ADS" },
          { option: "2- Criar algo que as pessoas vão lembrar, algo que cause uma boa impressão visual", course: "Web Design, Designer Gráfico"},
          { option: "3- Ser capaz de organizar e interpretar grandes quantidades de informação de forma clara e eficiente ", course: "Operador de Dados"},
          { option: "4- Ajudar as pessoas a alcançar seus próprios sucessos, promovendo uma boa comunicação e entendimento", course: "Soft Skills"},
          { option: "5- Liderar projetos e equipes que tenham impacto real em uma organização ou sociedade ", course: "Administração"},
          { option: "6- Ser uma fonte de conforto e cuidado para aqueles que precisam, melhorando suas vidas", course: "Profissional de Saúde"},
          { option: "7- Criar algo inovador e envolvente que inspire outras pessoas", course: "Desenvolvedor de Games"},
          { option: "8- Produzir materiais gráficos que transmitam mensagens poderosas e diretas", course: "Gráfico"},
          { option: "9- Alcançar o público certo e gerar resultados eficazes com estratégias digitais", course: "Marketing Digital"},
        ],
      },
      {
        id: "pergunta6",
        question: "Pergunta 6: Como você lida com situações que estão fora do seu controle?",
        answers: [
          { option: "1- Tento encontrar soluções alternativas que dependam das minhas habilidades técnicas", course: "T.I., ADS"},
          { option: "2- Tento me adaptar e buscar inspiração criativa dentro das limitações", course: "Web Design, Designer Gráfico"},
          { option: "3- Tento reorganizar as informações e trabalhar com o que tenho de forma lógica", course: "Operador de Dados"},
          { option: "4- Foco em ajudar os outros a lidar com a situação, oferecendo suporte emocional", course: "Soft Skills"},
          { option: "5- Busco formas de retomar o controle da situação com liderança e planejamento", course: "Administração"},
          { option: "6- Aceito a situação e faço o melhor que posso para ajudar as pessoas envolvidas", course: "Profissional de Saúde"},
          { option: "7- Tento reimaginar a situação, criando soluções criativas e alternativas", course: "Desenvolvedor de Games"},
          { option: "8- Encontro maneiras de ajustar o projeto gráfico conforme a necessidade do cliente", course: "Gráfico"},
          { option: "9- Redireciono as estratégias digitais para alcançar os melhores resultados possíveis ", course: "Marketing Digital"},
        ],
      },
      {
        id: "pergunta7",
        question: "Pergunta 7: O que é mais importante para você em um ambiente de trabalho?",
        answers: [
          { option: "1- Ter acesso a novas tecnologias e desafios complexos", course: "T.I., ADS"},
          { option: "2- Um ambiente que estimule a criatividade e a expressão visual ", course: "Web Design, Designer Gráfico"},
          { option: "3- Um espaço organizado e focado, onde eu possa trabalhar com dados e sistemas", course: "Operador de Dados"},
          { option: "4- Um lugar onde eu possa colaborar e desenvolver a comunicação com outras pessoas", course: "Soft Skills"},
          { option: "5- Um ambiente onde posso liderar e gerir projetos importantes", course: "Administração"},
          { option: "6- Um ambiente onde posso cuidar diretamente das pessoas e fazer a diferença na vida delas", course: "Profissional de Saúde" },
          { option: "7- Um espaço criativo onde posso imaginar e desenvolver novas ideias e jogos", course: "Desenvolvedor de Games"},
          { option: "8- Um ambiente que me permita trabalhar com comunicação visual e impressão", course: "Gráfico"},
          { option: "9- Um ambiente dinâmico onde estratégias e resultados de marketing estão sempre em evolução", course: "Marketing Digital"},
        ],
      },
      {
        id: "pergunta8",
        question: "Pergunta 8: Como você lida com o fracasso?",
        answers: [
          { option: "1- Vejo o fracasso como uma oportunidade de melhorar minhas habilidades técnicas", course: "T.I., ADS"},
          { option: "2- Transformo o fracasso em inspiração para uma nova criação", course: "Web Design, Designer Gráfico"},
          { option: "3- Analiso o que deu errado para melhorar o processo no futuro", course: "Operador de Dados"},
          { option: "4- Uso o fracasso como uma oportunidade para aprender e ajudar outros a lidar com suas emoções", course: "Soft Skills"},
          { option: "5- Vejo o fracasso como um passo natural no caminho para o sucesso e aprendo com ele", course: "Administração"},
          { option: "6- Aceito o fracasso como parte do processo de cuidar das pessoas, e tento melhorar continuamente", course: "Profissional de Saúde"},
          { option: "7- Uso o fracasso como uma forma de melhorar minhas histórias e criações", course: "Desenvolvedor de Games"},
          { option: "8- Vejo o fracasso como uma oportunidade de refinar minhas peças gráficas", course: "Gráfico"},
          { option: "9- Reavalio a campanha e ajusto as estratégias para obter melhores resultados no futuro", course: "Marketing Digital"},
        ],
      },
      {
        id: "pergunta9",
        question: "Pergunta 9: O que te faz sentir mais conectado com os outros?",
        answers: [
          { option: "1- Colaborar em projetos tecnológicos e resolver problemas em equipe", course: "T.I., ADS"},
          { option: "2- Compartilhar minhas criações visuais e ouvir feedback sobre elas", course: "Web Design, Designer Gráfico"},
          { option: "3- Ajudar a organizar e estruturar informações que ajudam as pessoas", course: "Operador de Dados" },
          { option: "4- Estar presente para os outros, ouvindo e ajudando-os a se expressarem melhor", course: "Soft Skills"},
          { option: "5- Trabalhar em equipe para alcançar metas e resolver problemas organizacionais", course: "Administração"},
          { option: "6- Cuidar das necessidades dos outros, mostrando empatia e compreensão", course: "Profissional de Saúde"},
          { option: "7- Criar algo em conjunto, como um jogo ou uma experiência que diverte as pessoas", course: "Desenvolvedor de Games"},
          { option: "8- Colaborar em projetos gráficos que comunicam mensagens importantes", course: "Gráfico"},
          { option: "9- Desenvolver campanhas que atingem o público de forma impactante e positiva", course: "Marketing Digital"},
        ],
      },
      {
        id: "pergunta10",
        question: "Pergunta 10: Ao realizar uma tarefa em grupo, você prefere:",
        answers: [
          { option: "1- Assumir o comando e tomar decisões rápidas.", profile: "Dominância" },
          { option: "2- Motivar e engajar os outros com ideias e sugestões. ", profile: "Influência" },
          { option: "3- Garantir que todos se sintam confortáveis e seguros no grupo. ", profile: "Estabilidade" },
          { option: "4- Organizar as etapas e garantir que cada detalhe seja seguido corretamente. ", profile: "Conformidade" },
        ],
      },
      {
        id: "pergunta11",
        question: "Pergunta 11: Quando enfrenta um desafio no trabalho ou nos estudos, você tende a:",
        answers: [
          { option: "1- Resolver o problema rapidamente, focando nos resultados.", profile: "Dominância" },
          { option: "2- Buscar apoio e opiniões de outras pessoas para encontrar a solução. ", profile: "Influência" },
          { option: "3- Agir com calma, analisando o impacto de cada escolha.", profile: "Estabilidade" },
          { option: "4- Seguir regras e procedimentos para encontrar a melhor solução. ", profile: "Conformidade"},
        ],
      },
      {
        id: "pergunta12",
        question: "Pergunta 12: Qual dessas atividades mais lhe atrai?",
        answers: [
          { option: "1- Resolver problemas matemáticos ou desafios lógicos.", field: "Exatas Matemática e Lógica" },
          { option: "2- Escrever textos ou analisar questões sociais.", field: "Humanas Letras e Ciências Sociais"},
          { option: "3- Trabalhar com experimentos ou descobrir como algo funciona. ", field: "Exatas Ciências e Tecnologia"},
          { option: "4- Entender o comportamento humano e ajudar pessoas.", field: "Humanas Psicologia e Comportamento"},
        ],
      },
      {
        id: "pergunta13",
        question: "Pergunta 13: Diante de um novo projeto, o que mais chama sua atenção?",
        answers: [
          { option: "1- Como estruturar e medir os resultados.", field: "Exatas Planejamento e Engenharia"},
          { option: "2- Como engajar as pessoas e comunicar ideias.", field: "Humanas Comunicação e Marketing"},
          { option: "3- Quais tecnologias podem ser usadas para otimizar o processo.", field: "Exatas Tecnologia e Inovação"},
          { option: "4- Como o projeto pode impactar positivamente a vida das pessoas.", field: "Humanas Desenvolvimento Social"},
        ],
      },
  ];